/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_deepresearch_deepResearch_addEvidence_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'criterionIds': z.array(z.string()).readonly().optional(),
  'source': z.string().readonly(),
  'url': z.string().readonly().optional(),
  'snippet': z.string().readonly().optional(),
  'claim': z.string().readonly(),
  'confidence': z.union([z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_addEvidence_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'question': z.string().readonly(),
  'goal': z.string().readonly(),
  'constraints': z.string().readonly(),
  'seedText': z.string().readonly(),
  'depth': z.union([z.literal("quick"), z.literal("standard"), z.literal("deep")]).readonly(),
  'phase': z.union([z.literal("failed"), z.literal("planning"), z.literal("awaiting_plan_confirm"), z.literal("investigating"), z.literal("ready_for_report"), z.literal("incomplete"), z.literal("writing"), z.literal("done"), z.literal("aborted")]).readonly(),
  'planConfirmed': z.boolean().readonly(),
  'questions': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'text': z.string().readonly(),
  'dependsOn': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'status': z.union([z.literal("running"), z.literal("failed"), z.literal("pending"), z.literal("covered"), z.literal("partial"), z.literal("blocked")]).readonly(),
  'criteria': z.array(z.object({
  'id': z.string().readonly(),
  'text': z.string().readonly(),
  'status': z.union([z.literal("covered"), z.literal("partial"), z.literal("blocked"), z.literal("missing"), z.literal("conflicted")]).readonly(),
  'summary': z.string().readonly(),
  'gap': z.string().readonly(),
})).readonly(),
})).readonly(),
  'evidence': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'criterionIds': z.array(z.string()).readonly(),
  'source': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'snippet': z.string().readonly(),
  'claim': z.string().readonly(),
  'confidence': z.union([z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'createdAt': z.number().readonly(),
})).readonly(),
  'conclusions': z.array(z.string()).readonly(),
  'limitations': z.array(z.string()).readonly(),
  'report': z.union([z.literal(null), z.string()]).readonly(),
  'budget': z.object({
  'maxSearches': z.number().readonly(),
  'maxFetches': z.number().readonly(),
  'searchesUsed': z.number().readonly(),
  'fetchesUsed': z.number().readonly(),
}).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_complete_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'report': z.string().readonly(),
  'conclusions': z.array(z.string()).readonly().optional(),
  'limitations': z.array(z.string()).readonly().optional(),
  'partial': z.boolean().readonly().optional(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_complete_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'question': z.string().readonly(),
  'goal': z.string().readonly(),
  'constraints': z.string().readonly(),
  'seedText': z.string().readonly(),
  'depth': z.union([z.literal("quick"), z.literal("standard"), z.literal("deep")]).readonly(),
  'phase': z.union([z.literal("failed"), z.literal("planning"), z.literal("awaiting_plan_confirm"), z.literal("investigating"), z.literal("ready_for_report"), z.literal("incomplete"), z.literal("writing"), z.literal("done"), z.literal("aborted")]).readonly(),
  'planConfirmed': z.boolean().readonly(),
  'questions': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'text': z.string().readonly(),
  'dependsOn': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'status': z.union([z.literal("running"), z.literal("failed"), z.literal("pending"), z.literal("covered"), z.literal("partial"), z.literal("blocked")]).readonly(),
  'criteria': z.array(z.object({
  'id': z.string().readonly(),
  'text': z.string().readonly(),
  'status': z.union([z.literal("covered"), z.literal("partial"), z.literal("blocked"), z.literal("missing"), z.literal("conflicted")]).readonly(),
  'summary': z.string().readonly(),
  'gap': z.string().readonly(),
})).readonly(),
})).readonly(),
  'evidence': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'criterionIds': z.array(z.string()).readonly(),
  'source': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'snippet': z.string().readonly(),
  'claim': z.string().readonly(),
  'confidence': z.union([z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'createdAt': z.number().readonly(),
})).readonly(),
  'conclusions': z.array(z.string()).readonly(),
  'limitations': z.array(z.string()).readonly(),
  'report': z.union([z.literal(null), z.string()]).readonly(),
  'budget': z.object({
  'maxSearches': z.number().readonly(),
  'maxFetches': z.number().readonly(),
  'searchesUsed': z.number().readonly(),
  'fetchesUsed': z.number().readonly(),
}).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_confirmPlan_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_confirmPlan_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'question': z.string().readonly(),
  'goal': z.string().readonly(),
  'constraints': z.string().readonly(),
  'seedText': z.string().readonly(),
  'depth': z.union([z.literal("quick"), z.literal("standard"), z.literal("deep")]).readonly(),
  'phase': z.union([z.literal("failed"), z.literal("planning"), z.literal("awaiting_plan_confirm"), z.literal("investigating"), z.literal("ready_for_report"), z.literal("incomplete"), z.literal("writing"), z.literal("done"), z.literal("aborted")]).readonly(),
  'planConfirmed': z.boolean().readonly(),
  'questions': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'text': z.string().readonly(),
  'dependsOn': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'status': z.union([z.literal("running"), z.literal("failed"), z.literal("pending"), z.literal("covered"), z.literal("partial"), z.literal("blocked")]).readonly(),
  'criteria': z.array(z.object({
  'id': z.string().readonly(),
  'text': z.string().readonly(),
  'status': z.union([z.literal("covered"), z.literal("partial"), z.literal("blocked"), z.literal("missing"), z.literal("conflicted")]).readonly(),
  'summary': z.string().readonly(),
  'gap': z.string().readonly(),
})).readonly(),
})).readonly(),
  'evidence': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'criterionIds': z.array(z.string()).readonly(),
  'source': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'snippet': z.string().readonly(),
  'claim': z.string().readonly(),
  'confidence': z.union([z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'createdAt': z.number().readonly(),
})).readonly(),
  'conclusions': z.array(z.string()).readonly(),
  'limitations': z.array(z.string()).readonly(),
  'report': z.union([z.literal(null), z.string()]).readonly(),
  'budget': z.object({
  'maxSearches': z.number().readonly(),
  'maxFetches': z.number().readonly(),
  'searchesUsed': z.number().readonly(),
  'fetchesUsed': z.number().readonly(),
}).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_delete_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_delete_result$schema = z.object({
  'deleted': z.boolean().readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_fail_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'reason': z.string().readonly(),
  'aborted': z.boolean().readonly().optional(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_fail_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'question': z.string().readonly(),
  'goal': z.string().readonly(),
  'constraints': z.string().readonly(),
  'seedText': z.string().readonly(),
  'depth': z.union([z.literal("quick"), z.literal("standard"), z.literal("deep")]).readonly(),
  'phase': z.union([z.literal("failed"), z.literal("planning"), z.literal("awaiting_plan_confirm"), z.literal("investigating"), z.literal("ready_for_report"), z.literal("incomplete"), z.literal("writing"), z.literal("done"), z.literal("aborted")]).readonly(),
  'planConfirmed': z.boolean().readonly(),
  'questions': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'text': z.string().readonly(),
  'dependsOn': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'status': z.union([z.literal("running"), z.literal("failed"), z.literal("pending"), z.literal("covered"), z.literal("partial"), z.literal("blocked")]).readonly(),
  'criteria': z.array(z.object({
  'id': z.string().readonly(),
  'text': z.string().readonly(),
  'status': z.union([z.literal("covered"), z.literal("partial"), z.literal("blocked"), z.literal("missing"), z.literal("conflicted")]).readonly(),
  'summary': z.string().readonly(),
  'gap': z.string().readonly(),
})).readonly(),
})).readonly(),
  'evidence': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'criterionIds': z.array(z.string()).readonly(),
  'source': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'snippet': z.string().readonly(),
  'claim': z.string().readonly(),
  'confidence': z.union([z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'createdAt': z.number().readonly(),
})).readonly(),
  'conclusions': z.array(z.string()).readonly(),
  'limitations': z.array(z.string()).readonly(),
  'report': z.union([z.literal(null), z.string()]).readonly(),
  'budget': z.object({
  'maxSearches': z.number().readonly(),
  'maxFetches': z.number().readonly(),
  'searchesUsed': z.number().readonly(),
  'fetchesUsed': z.number().readonly(),
}).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_get_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_get_result$schema = z.union([z.literal(null), z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'question': z.string().readonly(),
  'goal': z.string().readonly(),
  'constraints': z.string().readonly(),
  'seedText': z.string().readonly(),
  'depth': z.union([z.literal("quick"), z.literal("standard"), z.literal("deep")]).readonly(),
  'phase': z.union([z.literal("failed"), z.literal("planning"), z.literal("awaiting_plan_confirm"), z.literal("investigating"), z.literal("ready_for_report"), z.literal("incomplete"), z.literal("writing"), z.literal("done"), z.literal("aborted")]).readonly(),
  'planConfirmed': z.boolean().readonly(),
  'questions': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'text': z.string().readonly(),
  'dependsOn': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'status': z.union([z.literal("running"), z.literal("failed"), z.literal("pending"), z.literal("covered"), z.literal("partial"), z.literal("blocked")]).readonly(),
  'criteria': z.array(z.object({
  'id': z.string().readonly(),
  'text': z.string().readonly(),
  'status': z.union([z.literal("covered"), z.literal("partial"), z.literal("blocked"), z.literal("missing"), z.literal("conflicted")]).readonly(),
  'summary': z.string().readonly(),
  'gap': z.string().readonly(),
})).readonly(),
})).readonly(),
  'evidence': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'criterionIds': z.array(z.string()).readonly(),
  'source': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'snippet': z.string().readonly(),
  'claim': z.string().readonly(),
  'confidence': z.union([z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'createdAt': z.number().readonly(),
})).readonly(),
  'conclusions': z.array(z.string()).readonly(),
  'limitations': z.array(z.string()).readonly(),
  'report': z.union([z.literal(null), z.string()]).readonly(),
  'budget': z.object({
  'maxSearches': z.number().readonly(),
  'maxFetches': z.number().readonly(),
  'searchesUsed': z.number().readonly(),
  'fetchesUsed': z.number().readonly(),
}).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})])
const _deepseek_ai_dsh_deepresearch_deepResearch_list_parameter_0$schema = z.object({
  'query': z.string().readonly().optional(),
  'phase': z.union([z.literal("failed"), z.literal("planning"), z.literal("awaiting_plan_confirm"), z.literal("investigating"), z.literal("ready_for_report"), z.literal("incomplete"), z.literal("writing"), z.literal("done"), z.literal("aborted")]).readonly().optional(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_list_result$schema = z.object({
  'projects': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'question': z.string().readonly(),
  'goal': z.string().readonly(),
  'constraints': z.string().readonly(),
  'seedText': z.string().readonly(),
  'depth': z.union([z.literal("quick"), z.literal("standard"), z.literal("deep")]).readonly(),
  'phase': z.union([z.literal("failed"), z.literal("planning"), z.literal("awaiting_plan_confirm"), z.literal("investigating"), z.literal("ready_for_report"), z.literal("incomplete"), z.literal("writing"), z.literal("done"), z.literal("aborted")]).readonly(),
  'planConfirmed': z.boolean().readonly(),
  'questions': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'text': z.string().readonly(),
  'dependsOn': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'status': z.union([z.literal("running"), z.literal("failed"), z.literal("pending"), z.literal("covered"), z.literal("partial"), z.literal("blocked")]).readonly(),
  'criteria': z.array(z.object({
  'id': z.string().readonly(),
  'text': z.string().readonly(),
  'status': z.union([z.literal("covered"), z.literal("partial"), z.literal("blocked"), z.literal("missing"), z.literal("conflicted")]).readonly(),
  'summary': z.string().readonly(),
  'gap': z.string().readonly(),
})).readonly(),
})).readonly(),
  'evidence': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'criterionIds': z.array(z.string()).readonly(),
  'source': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'snippet': z.string().readonly(),
  'claim': z.string().readonly(),
  'confidence': z.union([z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'createdAt': z.number().readonly(),
})).readonly(),
  'conclusions': z.array(z.string()).readonly(),
  'limitations': z.array(z.string()).readonly(),
  'report': z.union([z.literal(null), z.string()]).readonly(),
  'budget': z.object({
  'maxSearches': z.number().readonly(),
  'maxFetches': z.number().readonly(),
  'searchesUsed': z.number().readonly(),
  'fetchesUsed': z.number().readonly(),
}).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})).readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_start_parameter_0$schema = z.object({
  'title': z.string().readonly().optional(),
  'question': z.string().readonly(),
  'goal': z.string().readonly().optional(),
  'constraints': z.string().readonly().optional(),
  'seedText': z.string().readonly().optional(),
  'depth': z.union([z.literal("quick"), z.literal("standard"), z.literal("deep")]).readonly(),
  'questions': z.array(z.object({
  'text': z.string().readonly(),
  'criteria': z.array(z.string()).readonly(),
  'dependsOn': z.array(z.number()).readonly().optional(),
})).readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_start_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'question': z.string().readonly(),
  'goal': z.string().readonly(),
  'constraints': z.string().readonly(),
  'seedText': z.string().readonly(),
  'depth': z.union([z.literal("quick"), z.literal("standard"), z.literal("deep")]).readonly(),
  'phase': z.union([z.literal("failed"), z.literal("planning"), z.literal("awaiting_plan_confirm"), z.literal("investigating"), z.literal("ready_for_report"), z.literal("incomplete"), z.literal("writing"), z.literal("done"), z.literal("aborted")]).readonly(),
  'planConfirmed': z.boolean().readonly(),
  'questions': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'text': z.string().readonly(),
  'dependsOn': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'status': z.union([z.literal("running"), z.literal("failed"), z.literal("pending"), z.literal("covered"), z.literal("partial"), z.literal("blocked")]).readonly(),
  'criteria': z.array(z.object({
  'id': z.string().readonly(),
  'text': z.string().readonly(),
  'status': z.union([z.literal("covered"), z.literal("partial"), z.literal("blocked"), z.literal("missing"), z.literal("conflicted")]).readonly(),
  'summary': z.string().readonly(),
  'gap': z.string().readonly(),
})).readonly(),
})).readonly(),
  'evidence': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'criterionIds': z.array(z.string()).readonly(),
  'source': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'snippet': z.string().readonly(),
  'claim': z.string().readonly(),
  'confidence': z.union([z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'createdAt': z.number().readonly(),
})).readonly(),
  'conclusions': z.array(z.string()).readonly(),
  'limitations': z.array(z.string()).readonly(),
  'report': z.union([z.literal(null), z.string()]).readonly(),
  'budget': z.object({
  'maxSearches': z.number().readonly(),
  'maxFetches': z.number().readonly(),
  'searchesUsed': z.number().readonly(),
  'fetchesUsed': z.number().readonly(),
}).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_updatePlan_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'goal': z.string().readonly(),
  'constraints': z.string().readonly(),
  'depth': z.union([z.literal("quick"), z.literal("standard"), z.literal("deep")]).readonly(),
  'questions': z.array(z.object({
  'text': z.string().readonly(),
  'criteria': z.array(z.string()).readonly(),
  'dependsOn': z.array(z.number()).readonly().optional(),
})).readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_updatePlan_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'question': z.string().readonly(),
  'goal': z.string().readonly(),
  'constraints': z.string().readonly(),
  'seedText': z.string().readonly(),
  'depth': z.union([z.literal("quick"), z.literal("standard"), z.literal("deep")]).readonly(),
  'phase': z.union([z.literal("failed"), z.literal("planning"), z.literal("awaiting_plan_confirm"), z.literal("investigating"), z.literal("ready_for_report"), z.literal("incomplete"), z.literal("writing"), z.literal("done"), z.literal("aborted")]).readonly(),
  'planConfirmed': z.boolean().readonly(),
  'questions': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'text': z.string().readonly(),
  'dependsOn': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'status': z.union([z.literal("running"), z.literal("failed"), z.literal("pending"), z.literal("covered"), z.literal("partial"), z.literal("blocked")]).readonly(),
  'criteria': z.array(z.object({
  'id': z.string().readonly(),
  'text': z.string().readonly(),
  'status': z.union([z.literal("covered"), z.literal("partial"), z.literal("blocked"), z.literal("missing"), z.literal("conflicted")]).readonly(),
  'summary': z.string().readonly(),
  'gap': z.string().readonly(),
})).readonly(),
})).readonly(),
  'evidence': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'criterionIds': z.array(z.string()).readonly(),
  'source': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'snippet': z.string().readonly(),
  'claim': z.string().readonly(),
  'confidence': z.union([z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'createdAt': z.number().readonly(),
})).readonly(),
  'conclusions': z.array(z.string()).readonly(),
  'limitations': z.array(z.string()).readonly(),
  'report': z.union([z.literal(null), z.string()]).readonly(),
  'budget': z.object({
  'maxSearches': z.number().readonly(),
  'maxFetches': z.number().readonly(),
  'searchesUsed': z.number().readonly(),
  'fetchesUsed': z.number().readonly(),
}).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_updateQuestion_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'status': z.union([z.literal("running"), z.literal("failed"), z.literal("pending"), z.literal("covered"), z.literal("partial"), z.literal("blocked")]).readonly(),
  'criteria': z.array(z.object({
  'id': z.string().readonly(),
  'text': z.string().readonly(),
  'status': z.union([z.literal("covered"), z.literal("partial"), z.literal("blocked"), z.literal("missing"), z.literal("conflicted")]).readonly(),
  'summary': z.string().readonly(),
  'gap': z.string().readonly(),
})).readonly().optional(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_updateQuestion_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'question': z.string().readonly(),
  'goal': z.string().readonly(),
  'constraints': z.string().readonly(),
  'seedText': z.string().readonly(),
  'depth': z.union([z.literal("quick"), z.literal("standard"), z.literal("deep")]).readonly(),
  'phase': z.union([z.literal("failed"), z.literal("planning"), z.literal("awaiting_plan_confirm"), z.literal("investigating"), z.literal("ready_for_report"), z.literal("incomplete"), z.literal("writing"), z.literal("done"), z.literal("aborted")]).readonly(),
  'planConfirmed': z.boolean().readonly(),
  'questions': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'text': z.string().readonly(),
  'dependsOn': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'status': z.union([z.literal("running"), z.literal("failed"), z.literal("pending"), z.literal("covered"), z.literal("partial"), z.literal("blocked")]).readonly(),
  'criteria': z.array(z.object({
  'id': z.string().readonly(),
  'text': z.string().readonly(),
  'status': z.union([z.literal("covered"), z.literal("partial"), z.literal("blocked"), z.literal("missing"), z.literal("conflicted")]).readonly(),
  'summary': z.string().readonly(),
  'gap': z.string().readonly(),
})).readonly(),
})).readonly(),
  'evidence': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'criterionIds': z.array(z.string()).readonly(),
  'source': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'snippet': z.string().readonly(),
  'claim': z.string().readonly(),
  'confidence': z.union([z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'createdAt': z.number().readonly(),
})).readonly(),
  'conclusions': z.array(z.string()).readonly(),
  'limitations': z.array(z.string()).readonly(),
  'report': z.union([z.literal(null), z.string()]).readonly(),
  'budget': z.object({
  'maxSearches': z.number().readonly(),
  'maxFetches': z.number().readonly(),
  'searchesUsed': z.number().readonly(),
  'fetchesUsed': z.number().readonly(),
}).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})

export const TYPERT = {
  package: '@deepseek-ai/dsh-deepresearch',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-deepresearch#deepResearch/addEvidence',
      service: 'deepResearch',
      namespace: 'deepResearch',
      method: 'addEvidence',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchEvidenceRequest',
            schema: _deepseek_ai_dsh_deepresearch_deepResearch_addEvidence_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchProject',
        schema: _deepseek_ai_dsh_deepresearch_deepResearch_addEvidence_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/deepresearch/src/index.ts","line":164,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-deepresearch#deepResearch/complete',
      service: 'deepResearch',
      namespace: 'deepResearch',
      method: 'complete',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchCompleteRequest',
            schema: _deepseek_ai_dsh_deepresearch_deepResearch_complete_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchProject',
        schema: _deepseek_ai_dsh_deepresearch_deepResearch_complete_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/deepresearch/src/index.ts","line":199,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-deepresearch#deepResearch/confirmPlan',
      service: 'deepResearch',
      namespace: 'deepResearch',
      method: 'confirmPlan',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchConfirmRequest',
            schema: _deepseek_ai_dsh_deepresearch_deepResearch_confirmPlan_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchProject',
        schema: _deepseek_ai_dsh_deepresearch_deepResearch_confirmPlan_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/deepresearch/src/index.ts","line":149,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-deepresearch#deepResearch/delete',
      service: 'deepResearch',
      namespace: 'deepResearch',
      method: 'delete',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchDeleteRequest',
            schema: _deepseek_ai_dsh_deepresearch_deepResearch_delete_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchDeleteResult',
        schema: _deepseek_ai_dsh_deepresearch_deepResearch_delete_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/deepresearch/src/index.ts","line":224,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-deepresearch#deepResearch/fail',
      service: 'deepResearch',
      namespace: 'deepResearch',
      method: 'fail',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchFailRequest',
            schema: _deepseek_ai_dsh_deepresearch_deepResearch_fail_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchProject',
        schema: _deepseek_ai_dsh_deepresearch_deepResearch_fail_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/deepresearch/src/index.ts","line":213,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-deepresearch#deepResearch/get',
      service: 'deepResearch',
      namespace: 'deepResearch',
      method: 'get',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchGetRequest',
            schema: _deepseek_ai_dsh_deepresearch_deepResearch_get_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepresearch#deepResearch/get:result',
        schema: _deepseek_ai_dsh_deepresearch_deepResearch_get_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/deepresearch/src/index.ts","line":111,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-deepresearch#deepResearch/list',
      service: 'deepResearch',
      namespace: 'deepResearch',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchListRequest',
            schema: _deepseek_ai_dsh_deepresearch_deepResearch_list_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchListResult',
        schema: _deepseek_ai_dsh_deepresearch_deepResearch_list_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/deepresearch/src/index.ts","line":100,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-deepresearch#deepResearch/start',
      service: 'deepResearch',
      namespace: 'deepResearch',
      method: 'start',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchStartRequest',
            schema: _deepseek_ai_dsh_deepresearch_deepResearch_start_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchProject',
        schema: _deepseek_ai_dsh_deepresearch_deepResearch_start_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/deepresearch/src/index.ts","line":119,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-deepresearch#deepResearch/updatePlan',
      service: 'deepResearch',
      namespace: 'deepResearch',
      method: 'updatePlan',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchPlanUpdateRequest',
            schema: _deepseek_ai_dsh_deepresearch_deepResearch_updatePlan_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchProject',
        schema: _deepseek_ai_dsh_deepresearch_deepResearch_updatePlan_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/deepresearch/src/index.ts","line":136,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-deepresearch#deepResearch/updateQuestion',
      service: 'deepResearch',
      namespace: 'deepResearch',
      method: 'updateQuestion',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchQuestionUpdateRequest',
            schema: _deepseek_ai_dsh_deepresearch_deepResearch_updateQuestion_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchProject',
        schema: _deepseek_ai_dsh_deepresearch_deepResearch_updateQuestion_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/deepresearch/src/index.ts","line":181,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Durable Codemini-style Deep Research project service.",
        "summary": "Durable Codemini-style Deep Research project service.",
        "tags": [],
        "jsDoc": "/** Durable Codemini-style Deep Research project service. */",
        "key": "deepResearch",
        "exportName": "DeepResearchService",
        "members": [
          {
            "kind": "method",
            "name": "list",
            "signature": "@Remote('list') list(request: ResearchListRequest): ResearchListResult",
            "summary": "List projects matching optional text and phase filters.",
            "jsDoc": "/**\n * List projects matching optional text and phase filters.\n * @param request - optional project filters.\n * @returns matching projects ordered by newest edit.\n */"
          },
          {
            "kind": "method",
            "name": "get",
            "signature": "@Remote('get') get(request: ResearchGetRequest): ResearchProject | null",
            "summary": "Read one exact project.",
            "jsDoc": "/**\n * Read one exact project.\n * @param request - project identity to read.\n * @returns detached project data, or null when absent.\n */"
          },
          {
            "kind": "method",
            "name": "start",
            "signature": "@Remote('start') start(request: ResearchStartRequest): Promise<ResearchProject>",
            "summary": "Create a draft plan with sub-questions and success criteria.",
            "jsDoc": "/**\n * Create a draft plan with sub-questions and success criteria.\n * @param request - research objective and initial question plan.\n * @returns the detached stored project.\n */"
          },
          {
            "kind": "method",
            "name": "updatePlan",
            "signature": "@Remote('updatePlan') updatePlan(request: ResearchPlanUpdateRequest): Promise<ResearchProject>",
            "summary": "Replace an unconfirmed project plan.",
            "jsDoc": "/**\n * Replace an unconfirmed project plan.\n * @param request - replacement plan and project identity.\n * @returns the updated detached project.\n */"
          },
          {
            "kind": "method",
            "name": "confirmPlan",
            "signature": "@Remote('confirmPlan') async confirmPlan(request: ResearchConfirmRequest): Promise<ResearchProject>",
            "summary": "Lock the plan and make the project ready for investigation.",
            "jsDoc": "/**\n * Lock the plan and make the project ready for investigation.\n * @param request - project identity to confirm.\n * @returns the updated detached project.\n */"
          },
          {
            "kind": "method",
            "name": "addEvidence",
            "signature": "@Remote('addEvidence') addEvidence(request: ResearchEvidenceRequest): Promise<ResearchProject>",
            "summary": "Attach one source-backed claim to a planned sub-question.",
            "jsDoc": "/**\n * Attach one source-backed claim to a planned sub-question.\n * @param request - evidence attribution and claim content.\n * @returns the updated detached project.\n */"
          },
          {
            "kind": "method",
            "name": "updateQuestion",
            "signature": "@Remote('updateQuestion') updateQuestion(request: ResearchQuestionUpdateRequest): Promise<ResearchProject>",
            "summary": "Update sub-question and criterion coverage after evidence review.",
            "jsDoc": "/**\n * Update sub-question and criterion coverage after evidence review.\n * @param request - reviewed question progress and criteria.\n * @returns the updated detached project.\n */"
          },
          {
            "kind": "method",
            "name": "complete",
            "signature": "@Remote('complete') complete(request: ResearchCompleteRequest): Promise<ResearchProject>",
            "summary": "Save a final or explicitly partial report with conclusions and limitations.",
            "jsDoc": "/**\n * Save a final or explicitly partial report with conclusions and limitations.\n * @param request - report content and completion state.\n * @returns the completed detached project.\n */"
          },
          {
            "kind": "method",
            "name": "fail",
            "signature": "@Remote('fail') fail(request: ResearchFailRequest): Promise<ResearchProject>",
            "summary": "Record an aborted or failed investigation without losing evidence.",
            "jsDoc": "/**\n * Record an aborted or failed investigation without losing evidence.\n * @param request - failure reason and termination type.\n * @returns the updated detached project.\n */"
          },
          {
            "kind": "method",
            "name": "delete",
            "signature": "@Remote('delete') delete(request: ResearchDeleteRequest): Promise<ResearchDeleteResult>",
            "summary": "Delete a project; absence is a stable successful outcome.",
            "jsDoc": "/**\n * Delete a project; absence is a stable successful outcome.\n * @param request - project identity to delete.\n * @returns whether the project existed.\n */"
          }
        ],
        "types": [
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "ResearchBudget",
            "declaration": "export interface ResearchBudget {\n    readonly maxSearches: number;\n    readonly maxFetches: number;\n    readonly searchesUsed: number;\n    readonly fetchesUsed: number;\n}"
          },
          {
            "name": "ResearchCompleteRequest",
            "declaration": "export interface ResearchCompleteRequest {\n    readonly id: ResearchId;\n    readonly report: string;\n    readonly conclusions?: string[];\n    readonly limitations?: string[];\n    readonly partial?: boolean;\n}"
          },
          {
            "name": "ResearchConfidence",
            "declaration": "export type ResearchConfidence = 'low' | 'medium' | 'high';"
          },
          {
            "name": "ResearchConfirmRequest",
            "declaration": "export interface ResearchConfirmRequest {\n    readonly id: ResearchId;\n}"
          },
          {
            "name": "ResearchCoverageStatus",
            "declaration": "export type ResearchCoverageStatus = 'missing' | 'partial' | 'covered' | 'conflicted' | 'blocked';"
          },
          {
            "name": "ResearchCriterion",
            "declaration": "export interface ResearchCriterion {\n    readonly id: string;\n    readonly text: string;\n    readonly status: ResearchCoverageStatus;\n    readonly summary: string;\n    readonly gap: string;\n}"
          },
          {
            "name": "ResearchDeleteRequest",
            "declaration": "export interface ResearchDeleteRequest {\n    readonly id: ResearchId;\n}"
          },
          {
            "name": "ResearchDeleteResult",
            "declaration": "export interface ResearchDeleteResult {\n    readonly deleted: boolean;\n}"
          },
          {
            "name": "ResearchDepth",
            "declaration": "export type ResearchDepth = 'quick' | 'standard' | 'deep';"
          },
          {
            "name": "ResearchEvidence",
            "declaration": "export interface ResearchEvidence {\n    readonly id: ResearchEvidenceId;\n    readonly questionId: ResearchQuestionId;\n    readonly criterionIds: string[];\n    readonly source: string;\n    readonly url: string | null;\n    readonly snippet: string;\n    readonly claim: string;\n    readonly confidence: ResearchConfidence;\n    readonly createdAt: number;\n}"
          },
          {
            "name": "ResearchEvidenceId",
            "declaration": "export type ResearchEvidenceId = Branded<'ResearchEvidenceId'>;"
          },
          {
            "name": "ResearchEvidenceRequest",
            "declaration": "export interface ResearchEvidenceRequest {\n    readonly id: ResearchId;\n    readonly questionId: ResearchQuestionId;\n    readonly criterionIds?: string[];\n    readonly source: string;\n    readonly url?: string;\n    readonly snippet?: string;\n    readonly claim: string;\n    readonly confidence: ResearchConfidence;\n}"
          },
          {
            "name": "ResearchFailRequest",
            "declaration": "export interface ResearchFailRequest {\n    readonly id: ResearchId;\n    readonly reason: string;\n    readonly aborted?: boolean;\n}"
          },
          {
            "name": "ResearchGetRequest",
            "declaration": "export interface ResearchGetRequest {\n    readonly id: ResearchId;\n}"
          },
          {
            "name": "ResearchId",
            "declaration": "export type ResearchId = Branded<'ResearchId'>;"
          },
          {
            "name": "ResearchListRequest",
            "declaration": "export interface ResearchListRequest {\n    readonly query?: string;\n    readonly phase?: ResearchPhase;\n}"
          },
          {
            "name": "ResearchListResult",
            "declaration": "export interface ResearchListResult {\n    readonly projects: ResearchProject[];\n}"
          },
          {
            "name": "ResearchPhase",
            "declaration": "export type ResearchPhase = 'planning' | 'awaiting_plan_confirm' | 'investigating' | 'ready_for_report' | 'incomplete' | 'writing' | 'done' | 'failed' | 'aborted';"
          },
          {
            "name": "ResearchPlanUpdateRequest",
            "declaration": "export interface ResearchPlanUpdateRequest {\n    readonly id: ResearchId;\n    readonly goal: string;\n    readonly constraints: string;\n    readonly depth: ResearchDepth;\n    readonly questions: Array<{ readonly text: string; readonly criteria: string[]; readonly dependsOn?: number[]; }>;\n}"
          },
          {
            "name": "ResearchProject",
            "declaration": "export interface ResearchProject {\n    readonly id: ResearchId;\n    readonly title: string;\n    readonly question: string;\n    readonly goal: string;\n    readonly constraints: string;\n    readonly seedText: string;\n    readonly depth: ResearchDepth;\n    readonly phase: ResearchPhase;\n    readonly planConfirmed: boolean;\n    readonly questions: ResearchQuestion[];\n    readonly evidence: ResearchEvidence[];\n    readonly conclusions: string[];\n    readonly limitations: string[];\n    readonly report: string | null;\n    readonly budget: ResearchBudget;\n    readonly createdAt: number;\n    readonly updatedAt: number;\n}"
          },
          {
            "name": "ResearchQuestion",
            "declaration": "export interface ResearchQuestion {\n    readonly id: ResearchQuestionId;\n    readonly text: string;\n    readonly dependsOn: ResearchQuestionId[];\n    readonly status: ResearchQuestionStatus;\n    readonly criteria: ResearchCriterion[];\n}"
          },
          {
            "name": "ResearchQuestionId",
            "declaration": "export type ResearchQuestionId = Branded<'ResearchQuestionId'>;"
          },
          {
            "name": "ResearchQuestionStatus",
            "declaration": "export type ResearchQuestionStatus = 'pending' | 'running' | 'covered' | 'partial' | 'blocked' | 'failed';"
          },
          {
            "name": "ResearchQuestionUpdateRequest",
            "declaration": "export interface ResearchQuestionUpdateRequest {\n    readonly id: ResearchId;\n    readonly questionId: ResearchQuestionId;\n    readonly status: ResearchQuestionStatus;\n    readonly criteria?: ResearchCriterion[];\n}"
          },
          {
            "name": "ResearchStartRequest",
            "declaration": "export interface ResearchStartRequest {\n    readonly title?: string;\n    readonly question: string;\n    readonly goal?: string;\n    readonly constraints?: string;\n    readonly seedText?: string;\n    readonly depth: ResearchDepth;\n    readonly questions: Array<{ readonly text: string; readonly criteria: string[]; readonly dependsOn?: number[]; }>;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
