/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_deepresearch_deepResearch_addEvidence_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'source': z.string().readonly(),
  'url': z.string().readonly().optional(),
  'summary': z.string().readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_addEvidence_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'question': z.string().readonly(),
  'depth': z.union([z.literal("quick"), z.literal("standard"), z.literal("deep")]).readonly(),
  'phase': z.union([z.literal("planning"), z.literal("researching"), z.literal("synthesizing"), z.literal("complete")]).readonly(),
  'plan': z.array(z.string()).readonly(),
  'evidence': z.array(z.object({
  'source': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'summary': z.string().readonly(),
})).readonly(),
  'report': z.union([z.literal(null), z.string()]).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_complete_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'report': z.string().readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_complete_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'question': z.string().readonly(),
  'depth': z.union([z.literal("quick"), z.literal("standard"), z.literal("deep")]).readonly(),
  'phase': z.union([z.literal("planning"), z.literal("researching"), z.literal("synthesizing"), z.literal("complete")]).readonly(),
  'plan': z.array(z.string()).readonly(),
  'evidence': z.array(z.object({
  'source': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'summary': z.string().readonly(),
})).readonly(),
  'report': z.union([z.literal(null), z.string()]).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_get_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_get_result$schema = z.union([z.literal(null), z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'question': z.string().readonly(),
  'depth': z.union([z.literal("quick"), z.literal("standard"), z.literal("deep")]).readonly(),
  'phase': z.union([z.literal("planning"), z.literal("researching"), z.literal("synthesizing"), z.literal("complete")]).readonly(),
  'plan': z.array(z.string()).readonly(),
  'evidence': z.array(z.object({
  'source': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'summary': z.string().readonly(),
})).readonly(),
  'report': z.union([z.literal(null), z.string()]).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})])
const _deepseek_ai_dsh_deepresearch_deepResearch_list_parameter_0$schema = z.object({
  'query': z.string().readonly().optional(),
  'phase': z.union([z.literal("planning"), z.literal("researching"), z.literal("synthesizing"), z.literal("complete")]).readonly().optional(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_list_result$schema = z.object({
  'projects': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'question': z.string().readonly(),
  'depth': z.union([z.literal("quick"), z.literal("standard"), z.literal("deep")]).readonly(),
  'phase': z.union([z.literal("planning"), z.literal("researching"), z.literal("synthesizing"), z.literal("complete")]).readonly(),
  'plan': z.array(z.string()).readonly(),
  'evidence': z.array(z.object({
  'source': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'summary': z.string().readonly(),
})).readonly(),
  'report': z.union([z.literal(null), z.string()]).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})).readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_start_parameter_0$schema = z.object({
  'question': z.string().readonly(),
  'depth': z.union([z.literal("quick"), z.literal("standard"), z.literal("deep")]).readonly(),
  'plan': z.array(z.string()).readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_start_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'question': z.string().readonly(),
  'depth': z.union([z.literal("quick"), z.literal("standard"), z.literal("deep")]).readonly(),
  'phase': z.union([z.literal("planning"), z.literal("researching"), z.literal("synthesizing"), z.literal("complete")]).readonly(),
  'plan': z.array(z.string()).readonly(),
  'evidence': z.array(z.object({
  'source': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'summary': z.string().readonly(),
})).readonly(),
  'report': z.union([z.literal(null), z.string()]).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})

export const TYPERT = {
  package: '@deepseek-ai/dsh-deepresearch',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-deepresearch#deepResearch/addEvidence',
      service: 'deepResearch',
      namespace: 'deepResearch',
      method: 'addEvidence',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchEvidenceRequest',
            schema: _deepseek_ai_dsh_deepresearch_deepResearch_addEvidence_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchProject',
        schema: _deepseek_ai_dsh_deepresearch_deepResearch_addEvidence_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/deepresearch/src/index.ts","line":150,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-deepresearch#deepResearch/complete',
      service: 'deepResearch',
      namespace: 'deepResearch',
      method: 'complete',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchCompleteRequest',
            schema: _deepseek_ai_dsh_deepresearch_deepResearch_complete_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchProject',
        schema: _deepseek_ai_dsh_deepresearch_deepResearch_complete_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/deepresearch/src/index.ts","line":176,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-deepresearch#deepResearch/get',
      service: 'deepResearch',
      namespace: 'deepResearch',
      method: 'get',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchGetRequest',
            schema: _deepseek_ai_dsh_deepresearch_deepResearch_get_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepresearch#deepResearch/get:result',
        schema: _deepseek_ai_dsh_deepresearch_deepResearch_get_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/deepresearch/src/index.ts","line":116,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-deepresearch#deepResearch/list',
      service: 'deepResearch',
      namespace: 'deepResearch',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchListRequest',
            schema: _deepseek_ai_dsh_deepresearch_deepResearch_list_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchListResult',
        schema: _deepseek_ai_dsh_deepresearch_deepResearch_list_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/deepresearch/src/index.ts","line":103,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-deepresearch#deepResearch/start',
      service: 'deepResearch',
      namespace: 'deepResearch',
      method: 'start',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchStartRequest',
            schema: _deepseek_ai_dsh_deepresearch_deepResearch_start_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchProject',
        schema: _deepseek_ai_dsh_deepresearch_deepResearch_start_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/deepresearch/src/index.ts","line":123,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Deep-research project service.",
        "summary": "Deep-research project service.",
        "tags": [],
        "jsDoc": "/** Deep-research project service. */",
        "key": "deepResearch",
        "exportName": "DeepResearchService",
        "members": [
          {
            "kind": "method",
            "name": "list",
            "signature": "@Remote('list') list(request: ResearchListRequest): ResearchListResult",
            "summary": "List projects matching optional text and phase filters.",
            "jsDoc": "/** List projects matching optional text and phase filters. */"
          },
          {
            "kind": "method",
            "name": "get",
            "signature": "@Remote('get') get(request: ResearchGetRequest): ResearchProject | null",
            "summary": "Read one exact project.",
            "jsDoc": "/** Read one exact project. */"
          },
          {
            "kind": "method",
            "name": "start",
            "signature": "@Remote('start') start(request: ResearchStartRequest): Promise<ResearchProject>",
            "summary": "Create a project with a non-empty investigation plan.",
            "jsDoc": "/** Create a project with a non-empty investigation plan. */"
          },
          {
            "kind": "method",
            "name": "addEvidence",
            "signature": "@Remote('addEvidence') addEvidence(request: ResearchEvidenceRequest): Promise<ResearchProject>",
            "summary": "Attach one finding and move the project into active investigation.",
            "jsDoc": "/** Attach one finding and move the project into active investigation. */"
          },
          {
            "kind": "method",
            "name": "complete",
            "signature": "@Remote('complete') complete(request: ResearchCompleteRequest): Promise<ResearchProject>",
            "summary": "Save the final synthesis and close the project.",
            "jsDoc": "/** Save the final synthesis and close the project. */"
          }
        ],
        "types": [
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "ResearchCompleteRequest",
            "declaration": "export interface ResearchCompleteRequest {\n    readonly id: ResearchId;\n    readonly report: string;\n}"
          },
          {
            "name": "ResearchDepth",
            "declaration": "export type ResearchDepth = 'quick' | 'standard' | 'deep';"
          },
          {
            "name": "ResearchEvidence",
            "declaration": "export interface ResearchEvidence {\n    readonly source: string;\n    readonly url: string | null;\n    readonly summary: string;\n}"
          },
          {
            "name": "ResearchEvidenceRequest",
            "declaration": "export interface ResearchEvidenceRequest {\n    readonly id: ResearchId;\n    readonly source: string;\n    readonly url?: string;\n    readonly summary: string;\n}"
          },
          {
            "name": "ResearchGetRequest",
            "declaration": "export interface ResearchGetRequest {\n    readonly id: ResearchId;\n}"
          },
          {
            "name": "ResearchId",
            "declaration": "export type ResearchId = Branded<'ResearchId'>;"
          },
          {
            "name": "ResearchListRequest",
            "declaration": "export interface ResearchListRequest {\n    readonly query?: string;\n    readonly phase?: ResearchPhase;\n}"
          },
          {
            "name": "ResearchListResult",
            "declaration": "export interface ResearchListResult {\n    readonly projects: ResearchProject[];\n}"
          },
          {
            "name": "ResearchPhase",
            "declaration": "export type ResearchPhase = 'planning' | 'researching' | 'synthesizing' | 'complete';"
          },
          {
            "name": "ResearchProject",
            "declaration": "export interface ResearchProject {\n    readonly id: ResearchId;\n    readonly question: string;\n    readonly depth: ResearchDepth;\n    readonly phase: ResearchPhase;\n    readonly plan: string[];\n    readonly evidence: ResearchEvidence[];\n    readonly report: string | null;\n    readonly createdAt: number;\n    readonly updatedAt: number;\n}"
          },
          {
            "name": "ResearchStartRequest",
            "declaration": "export interface ResearchStartRequest {\n    readonly question: string;\n    readonly depth: ResearchDepth;\n    readonly plan: string[];\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
